# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bgImgList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelType', models.CharField(default='modelType', max_length=100)),
                ('modelPic', models.CharField(default='modelPic', max_length=100)),
                ('name', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardID', models.CharField(default='cardID', max_length=100)),
                ('cardType', models.CharField(default='cardType', max_length=100)),
                ('userID', models.CharField(default='userID', max_length=100)),
                ('createrID', models.CharField(default='createrID', max_length=100)),
                ('peopleName', models.CharField(default='peopleName', max_length=100)),
                ('phoneNum', models.CharField(default='phoneNum', max_length=100)),
                ('createTime', models.CharField(default='createTime', max_length=100)),
                ('cardModelType', models.CharField(default='cardModelType', max_length=100)),
                ('bgImgUrl', models.CharField(default='bgImgUrl', max_length=100)),
                ('logoImgUrl', models.CharField(default='logoImgUrl', max_length=1000)),
                ('companyName', models.CharField(default='companyName', max_length=32)),
                ('QQ', models.CharField(default='QQ', max_length=100)),
                ('Email', models.CharField(default='Email', max_length=100)),
                ('positionName', models.CharField(default='positionName', max_length=100)),
                ('address', models.CharField(default='positionName', max_length=100)),
                ('sharePeople', models.CharField(default='sharePeople', max_length=100)),
                ('EnglishName', models.CharField(default='EnglishName', max_length=100)),
                ('qrcodeID', models.CharField(default='qrcodeID', max_length=100)),
                ('qrcodeimage', models.CharField(default='qrcodeimage', max_length=100)),
                ('qrcodeModel', models.CharField(default='qrcodeModel', max_length=1000, null=True)),
                ('Latitude', models.CharField(default='Latitude', max_length=1000, null=True)),
                ('longitude', models.CharField(default='longitude', max_length=1000, null=True)),
                ('tagID', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='qrcodeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='myQrcodeID', max_length=100)),
                ('myQrcodeID', models.CharField(default='myQrcodeID', max_length=100)),
                ('userID', models.CharField(default='userID', max_length=100)),
                ('isUsing', models.CharField(default='isUsing', max_length=100)),
                ('qrcodeimage', models.CharField(default='qrcodeimage', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tagTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=1000, null=True)),
                ('tagID', models.CharField(default='', max_length=1000, null=True)),
                ('price', models.CharField(default='0', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openID', models.CharField(default='openID', max_length=100)),
            ],
        ),
    ]
